name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout
      uses: actions/checkout@v2
    
    - name: install haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.0.5

    - name: Run Compiler.Parser tests
      run: haxe --run GlarespeakC glareTestCompiler/*.glare

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
